{% set name = "pluggy" %}
{% set version = "0.13.0" %}
{% set sha256 = "fa5fa1622fa6dd5c030e9cad086fa19ef6a0cf6d7a2d12318e10cb49d6d68f34" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name [0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  build:
    - pip
    - setuptools_scm

  run:
    - python
    - importlib_metadata >=0.12  # [py<38]

test:
  imports:
    - pluggy

about:
  home: https://github.com/pytest-dev/pluggy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Plugin registration and hook calling for Python'
  doc_url: https://pluggy.readthedocs.io/en/latest/
  dev_url: https://github.com/pytest-dev/pluggy/

extra:
  recipe-maintainers:
    - JohnGreeley
    - nicoddemus
