travis:
  secure:
    BINSTAR_TOKEN: pJanGs9i821P+tdUc2Jcz4F3BATZwI/b96FJch8mD+fBpklNSP4AXBfUApCWZIQXf1uQbyk+e5CoeB97l91dFYFiQWVyUgxGuThoOhqFZKFDoxkehj/2Rm0RbKldE5FIi+76EVw0E/Gr3LzvSS/LI5yTp0Ff5YfF6tYYvDanTAVBYtuFF94GD9nmuYWGGGMkrv2EzBilpD8HRI7ivc6oOXs58DIgr33DmFXsCZUKWrz8WSVZB3k7+I+qkLHi1Vlp+TEFRcfRRCPG2CAfsuoOxTiBmxVyHoPW5gSKmJTW21IPsjuKNfT4wmjiCX7+eKpy9wmYh7PVi1PnBRZroSRcJCVEUXchYOsDgqUTDr/whujB5vANiSV1+4IfcdvAuAR9pKh3/9Gye0SV5bkTvwDI1wwAVyR2aTNWTaIQo2wZD0zb2Cej5Ynr97w7dM/uSPA/NuRBhTHxqUqMu1z0beTyN5dtuNoWI7DR5kyaSHYsm6vvV7QG3lceOADjz9tnmSd4/MSwwIiVshbH2521+7DkaxJz7UEQ2MMAXWrC5biikq3mUCH8KzyL9cDwXVsTfcqfL0R7z1qsYHfv/4KndnRxsHPbLl8vumSIQFfL9TEoEDC4OmLQhWZ9OmsLWqTKVNYGPa/HaCrc8kf3hDYtW5n4UZVFXbZIoZNaj4AuEkS+WRo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
